#ifndef COMPILER_PASSES_LEX_H
#define COMPILER_PASSES_LEX_H

#include "sys/string_view.h"

struct token {
	enum {
		TOKEN_IDENTIFIER,
		TOKEN_CONSTANT,
		TOKEN_KEYWORD_RETURN,
		TOKEN_KEYWORD_VOID,
		TOKEN_KEYWORD_INT,
		TOKEN_PAREN_OPEN,
		TOKEN_PAREN_CLOSE,
		TOKEN_BRACE_OPEN,
		TOKEN_BRACE_CLOSE,
		TOKEN_SEMICOLON,
		TOKEN_TILDE,
		TOKEN_HYPHEN_HYPHEN,
		TOKEN_HYPHEN,
		TOKEN_PLUS_SIGN,
		TOKEN_ASTERISK,
		TOKEN_FORWARD_SLASH,
		TOKEN_PERCENT_SIGN,
		TOKEN_EXCLAMATION_MARK,
		TOKEN_EXCLAMATION_MARK_EQUAL_SIGN,
		TOKEN_AMPERSAND,
		TOKEN_AMPERSAND_AMPERSAND,
		TOKEN_AMPERSAND_EQUAL_SIGN,
		TOKEN_VERTICAL_BAR,
		TOKEN_VERTICAL_BAR_VERTICAL_BAR,
		TOKEN_VERTICAL_BAR_EQUAL_SIGN,
		TOKEN_EQUAL_SIGN,
		TOKEN_EQUAL_SIGN_EQUAL_SIGN,
		TOKEN_LESS_THAN,
		TOKEN_LESS_THAN_LESS_THAN,
		TOKEN_LESS_THAN_EQUAL_SIGN,
		TOKEN_GREATER_THAN,
		TOKEN_GREATER_THAN_GREATER_THAN,
		TOKEN_GREATER_THAN_EQUAL_SIGN,
	} token_type;
	struct string_view val;
	struct token *next;
};

#endif
